apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.fullname" . }}-jobservice"
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  app.conf: |+
    appname = jobservice
    runmode = prod

    [prod]
    httpport = 8080
