apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-registry"
  namespace: class100-ops
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 5000
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry