apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  namespace: kube-apps
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: adminserver