apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-mysql"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  mysqlRootPassword: {{ .Values.mysql.pass | b64enc | quote }}
